# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signup(self):
    self.driver.get("http://localhost:5500/")
    self.driver.set_window_size(1294, 734)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    self.driver.find_element(By.ID, "fname").click()
    self.driver.find_element(By.ID, "fname").send_keys("jema")
    self.driver.find_element(By.ID, "lname").send_keys("kurian")
    self.driver.find_element(By.ID, "email").send_keys("jema@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
